server:
  port: 8081
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

